### ISSUE TITLE
Add a note about required credentials.

### ISSUE THREAD

**Issue by RayBB** [turbot/steampipe-mod-community-tracker#1]
It took me a little tinkering to figure out I needed to give it a token with at least `read:org` and `read:user` permissions.
Since I was doing this on a public repo I hoped that it wouldn't need anything 🤷 

So would be nice to add this to the docs!

This is mostly because when I add `read:org` it says:
```
ERROR: rpc error: code = Unknown desc = Your token has not been granted the required scopes to execute this query. The 'email' field requires one of the following scopes: ['user:email', 'read:user'], but your token has only been granted the: ['read:org'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens. (SQLSTATE HV000)
```
But actually, `user:email` isn't enough and `read:user` is required.

**Comment by rajlearner17** [comment]
@RayBB Thanks for raising this issue!

Can you please provide more context and reference link? 
As we see, the required permissions mentioned in the https://hub.steampipe.io/plugins/turbot/github doc 

You must create a [personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) and assign the following scopes:
    - repo (all)
    - read:org
    - gist
    - read:user
    - user:email

**Comment by RayBB** [comment]
Yes would be great to link to that page from this repo. Just to say tokens are needed to run this and see more on X page.

**Comment by rajlearner17** [comment]
@RayBB Understood; you want to refer to GitHub plugin doc references to the README doc of this repo. Point noted.

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-mod-community-tracker/pull/2
